### ISSUE TITLE
Error 'let rain3h = jsonObj.rain'

### ISSUE THREAD

**Issue by raffaelps** [CICCIOSGAMINO/openweather-apis#19]
Hello,

When I use the 3.3.0 version, this errors occur:

/app/node_modules/openweather-apis/index.js:173
let rain3h = jsonObj.rain;
^^^^^^
SyntaxError: Unexpected identifier

Thanks

**Comment by CICCIOSGAMINO** [comment]
I think you need to update the Node.js version ...
