### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Dynrothe** [CICCIOSGAMINO/openweather-apis#22]
How could I fix this error: 
`C:\Users\\Desktop\\node_modules\openweather-apis\index.js:155
      return callback(err, (jsonObj.weather)[0].description);
                                            ^
TypeError: Cannot read property '0' of undefined`
I get it when it can't find the city

EDIT: I fixed it myself

**Comment by Longlius** [comment]
How'd you fix it?

**Comment by Dynrothe** [comment]
Made this modification in the module's index.js under "active functions()". Might not be the best way to do it but it's enough for me
`  function getDesc(callback){
    getData(buildPath(), function(err,jsonObj){
      if (jsonObj.weather === undefined) {
        return;
      } else {
      return callback(err, (jsonObj.weather)[0].description);
      }
    });
  };`

**Comment by CICCIOSGAMINO** [comment]
I think its better get the error and handle it in the main section the openweather-apis is used rather then silence return ....
