### ISSUE TITLE
City,CountryCode broken

### ISSUE THREAD

**Issue by fcaza** [CICCIOSGAMINO/openweather-apis#28]
City,CountryCode is now broken
try:
weather.setCity('Roma,IT');

Actually, it didn't worked as well in 4.0.0
It's because of encodeURIComponent in setCity?

**Comment by velsa** [comment]
Looks like a real issue. 
E.g. if you have a city name with a space in it, space is translated into `%2520` instead of `%20`

**Comment by CICCIOSGAMINO** [comment]
I'm working on ... i'll be solved in the v5.0.0 coming soon !!

**Comment by knoguchi** [comment]
The string is encoded twice.  That's why ` ` encoded to `%20` and encoded again to `%2520`

**Comment by naofireblade** [comment]
I created a PR to fix this.
