### ISSUE TITLE
"Invalid API key" when using getWeatherForecastForDays

### ISSUE THREAD

**Issue by NoobyBoy** [CICCIOSGAMINO/openweather-apis#29]
version : 4.1.0

When I'm using others method it works perfectly fine (ej: getAllWeather, getTemperature, ...) but when I use getWeatherForecastForDays  like this:
       
```
      weather.setCity(city);
         weather.getWeatherForecastForDays(time, function(err, obj){
             if (err)
                 console.log(err);
             console.log(obj);
```
I get : 
{ cod: 401,
  message: 'Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.' }

**Comment by CICCIOSGAMINO** [comment]
You need payment account and API KEY for that functionality ..... as in the comment !

**Comment by NoobyBoy** [comment]
> You need payment account and API KEY for that functionality ..... as in the comment !

Ok I probably missed it, thanks.
