### ISSUE TITLE
getTemp throws error when invalid API Key is used

### ISSUE THREAD

**Issue by mastasky** [CICCIOSGAMINO/openweather-apis#30]
Since the function tries to access a deeply nested value which doesn't exist, we get an exception which isn't caught and forwarded to the callback.

https://github.com/CICCIOSGAMINO/openweather-apis/blob/71081eff2c84dcce6e8dbc78877639f0266caaae/index.js#L162

Repro:

- Create a script that instantatias weather with an invalid API key
- Call the getTemperature function

**Comment by jemxz** [comment]
This error also occurs when a valid API key is used. Is there a fix to it?

**Comment by CICCIOSGAMINO** [comment]
I'm working on ...

**Comment by CICCIOSGAMINO** [comment]
Solved in the next version ... i'll be v5.0.0

**Comment by jemxz** [comment]
nice

**Comment by bayoudhi** [comment]
Hello guys, I think this issue is already fixed in this merged PR #41
