### ISSUE TITLE
Support for browser (and react-native)

### ISSUE THREAD

**Issue by namnm** [CICCIOSGAMINO/openweather-apis#32]
Instead of using http/https package, we can use browser friendly package like fetch, axios, request... All those packages should work with Node and have ReactNative bindings.

**Comment by CICCIOSGAMINO** [comment]
I'm thinking about for the v5 ! Thanks

**Comment by namnm** [comment]
@CICCIOSGAMINO Axios is the way https://github.com/axios/axios

**Comment by CICCIOSGAMINO** [comment]
I'm thinking at a function like this to init the right fetch .... with the use of node-fetch when in Node.js ... 
`// init the right Fetch (Node.js or Browser)
  async initFetch () {
    const isBrowser = new Function('try {return this===window;}catch(e){ return false;}')
    const isNode = new Function('try {return this===global;}catch(e){return false;}')

    // tests if global scope is binded to window
    if (isBrowser()) {
      console.log('Running under browser')
    }
    if (isNode()) {
      console.log('running under node.js')
      nodeFetch = await import('node-fetch')
      fetch = nodeFetch.default
    }
  }`

**Comment by namnm** [comment]
Yes this one can be a minimal set of changes, fetch is supported by default in browser and react-native.

**Comment by CICCIOSGAMINO** [comment]
Supported in v5.0.0-pre
