### ISSUE TITLE
getSmartJSON retrieves null

### ISSUE THREAD

**Issue by aeri** [CICCIOSGAMINO/openweather-apis#33]
When i am using the function getSmartJSON with the latest version of package and a valid API key it returns null.

The other functions like getTemperature or getAllWeather works well.

Why can this happen?

Using nodejs v12.16.1

**Comment by faustyn-p** [comment]
@aeri 

It turns out that the `getSmartJSON` function returns `error` and `response` (in this order).

```
      return callback(err,smartJSON);
```

Therefore, if you want to get a result, you should do it this way (for example):

```
		weather.getSmartJSON((err, response) => {
			console.log(response);
		});
```

**Comment by aeri** [comment]
Thank you @faustyn-p 
the documentation is wrong and I directly took that example.

@CICCIOSGAMINO please fix that
