### ISSUE TITLE
Add support for new OpenWeatherMap One Call API

### ISSUE THREAD

**Issue by naofireblade** [CICCIOSGAMINO/openweather-apis#35]
OWM added a new free API with more forecast days and a lot of more conditions. They aim to provide all the information that was provided by the discontinued dark sky api: https://openweathermap.org/api/one-call-api
https://openweathermap.org/darksky-openweather

**Comment by CICCIOSGAMINO** [comment]
Working on ..thanks !

**Comment by epollux** [comment]
Excellent, I was looking at this module and was looking for the OneCall support...glad the question was asked before. Looking forward to it.

**Comment by DustinJSilk** [comment]
Any updates on this?

**Comment by RabbitLabs** [comment]
Hi, I did a small patch for One Call API

[0001-Update-index.js.zip](https://github.com/CICCIOSGAMINO/openweather-apis/files/5511900/0001-Update-index.js.zip)

**Comment by CICCIOSGAMINO** [comment]
Would you make a pull request so i can verify and merge it eventually ?? Check the v.5.0.0-pre release ....
