### ISSUE TITLE
Does it support weather maps?

### ISSUE THREAD

**Issue by BronzW** [CICCIOSGAMINO/openweather-apis#42]
Can you fetch weather maps with this api wrapper? I tried to do weather.getTemperature() without setting a location, but then it throws an error.

```ts
return callback(err,jsonObj.main.temp);

TypeError: Cannot read property 'main' of null
```

**Comment by bayoudhi** [comment]
Hello @BronzW, I think you cannot get the temperature without setting one of these 4 options

From [Readme](https://github.com/CICCIOSGAMINO/openweather-apis#how-to-use)

``` From Readme
// set city by name
	weather.setCity('Fairplay');
 	// or set the coordinates (latitude,longitude)
	weather.setCoordinate(50.0467656, 20.0048731);
	// or set city by ID (recommended by OpenWeatherMap)
	weather.setCityId(4367872);

    // or set zip code
	weather.setZipCode(33615);
```

**Comment by BronzW** [comment]
Yes, but is there a function or method to get weather maps?

**Comment by bayoudhi** [comment]
No, unfortunately.

**Comment by CICCIOSGAMINO** [comment]
Can you explain what functionality is weather map ??
