### ISSUE TITLE
README Incorrect

### ISSUE THREAD

**Issue by SCKelemen** [CICCIOSGAMINO/openweather-apis#8]
In README:

    // check http://openweathermap.org/appid#get for get the APPID
    weather.setAPIID('ssdglnsdogdh441s91gs6');

Weather.setAPIID is undefined.

In your source weather.setAPPID is defined.

**Comment by CICCIOSGAMINO** [comment]
i can't get it ..... it has showed such as an example of APIID, you need to register on site to get yours !

**Comment by Err418** [comment]
The issue isnt with the key, it is with the documentation. The documentation says weather.setAPIID, but it should be weather.setAPPID. [ API ID vs APP ID ]

**Comment by Err418** [comment]
![image](https://cloud.githubusercontent.com/assets/4325375/11898741/34b64120-a568-11e5-9b8d-42e42e6f137a.png)

![image](https://cloud.githubusercontent.com/assets/4325375/11898772/584f0a4a-a568-11e5-952b-8a3bce8b6c50.png)

**Comment by CICCIOSGAMINO** [comment]
Updated !
